//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuriloSantos.PedidosApp.Domain.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MuriloSantos.PedidosApp.Domain.Messages.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O quantidade do item do pedido deve estar entre 0,01 e  999,99.
        /// </summary>
        public static string ItemPedido_Qtde_Invalida {
            get {
                return ResourceManager.GetString("ItemPedido_Qtde_Invalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor do item deve ser maior que zero.
        /// </summary>
        public static string ItemPedido_Valor_Invalido {
            get {
                return ResourceManager.GetString("ItemPedido_Valor_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data do pedido deve ser maior que a data atual.
        /// </summary>
        public static string Pedido_Data_Deve_Ser_Maior_Que_Atual {
            get {
                return ResourceManager.GetString("Pedido_Data_Deve_Ser_Maior_Que_Atual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O pedido deve possuir um ou mais itens..
        /// </summary>
        public static string Pedido_Deve_Possuir_Itens {
            get {
                return ResourceManager.GetString("Pedido_Deve_Possuir_Itens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O pedido não deve possuir itens repetidos..
        /// </summary>
        public static string Pedido_Itens_Nao_Devem_Repetir {
            get {
                return ResourceManager.GetString("Pedido_Itens_Nao_Devem_Repetir", resourceCulture);
            }
        }
    }
}
